blog/__init__.py
import logging
from logging.handlers import RotatingFileHandler

from flask import Flask, render_template
from flask_session import Session
from flask_wtf import CSRFProtect
from flask_wtf.csrf import generate_csrf
from redis import StrictRedis

from config import config
from .extensions import db, mail, moment, ckeditor

# 定义redis数据库
redis_store = None  # type: StrictRedis


def setup_log(config_name):
    """设置日志"""
    # 设置日志记录等级
    logging.basicConfig(level=config[config_name].LOG_LEVEL)  # 调试级别
    # 创建日志记录器，指明日志保存的路径、日志文件的大小和保存日志文件个数上限
    file_log_handler = RotatingFileHandler("logs/log", maxBytes=1024*1024*10, backupCount=10)
    # 创建日志记录的格式、日志等级、输入日志信息的文件名、行数、日志信息
    formatter = logging.Formatter("%(levelname)s %(filename)s:%(lineno)d %(message)s")
    # 为创建的日志记录器设置记录格式
    file_log_handler.setFormatter(formatter)
    # 为全局的日志工具对象添加日志记录器
    logging.getLogger().addHandler(file_log_handler)


def create_app(config_name):
    """创建app的工厂函数"""
    # 设置日志
    setup_log(config_name)
    # 创建flask的app对象
    app = Flask(__name__)
    # 加载配置
    app.config.from_object(config[config_name])
    # 导入扩展对象
    db.init_app(app)
    moment.init_app(app)
    mail.init_app(app)
    ckeditor.init_app(app)
    # 初始化redis数据库
    global redis_store
    redis_store = StrictRedis(host=config[config_name].REDIS_HOST,
                              port=config[config_name].REDIS_PORT,
                              decode_responses=True)
    # 设置session，使用flask_session中的session扩展，session用于记录用户的登录信息
    Session(app)
    # 设置csrf保护，防止csrf攻击
    CSRFProtect(app)

    # 注册蓝图
    from blog.modules.index import index_bp
    app.register_blueprint(index_bp)
    from blog.modules.auth import auth_bp
    app.register_blueprint(auth_bp)
    from blog.modules.admin import admin_bp
    app.register_blueprint(admin_bp)
    from blog.modules.article import article_bp
    app.register_blueprint(article_bp)

    @app.after_request
    def after_request(response):
        """每次前端请求之后响应之前生成随机的CSRF值,并放在响应的cookie中，下次请求会将之带回验证"""
        csrf_token = generate_csrf()
        response.set_cookie("csrf_token", csrf_token)
        return response

    # 设置全局的404页面，当有未知链接时重定向到此页面
    @app.errorhandler(404)
    def page_notfound(e):
        return render_template("blog/404.html")

    return app

blog/modules/__init__.py
# 项目的模块

blog/modules/admin/__init__.py
# 后台管理模块的蓝图
from flask import Blueprint, session, request, url_for, redirect

admin_bp = Blueprint("admin", __name__, url_prefix="/admin")

from . import views


@admin_bp.before_request
def check_admin():
    """校验管理员权限的请求钩子"""
    # 如果不是管理员，也不是访问管理员的登录页，则跳转到首页
    is_admin = session.get("is_admin", False)
    if not is_admin and not request.url.endswith(url_for("admin.login")):
        return redirect("/")

blog/modules/admin/views.py
# 管理模块的视图
import time
from datetime import datetime, timedelta

from flask import render_template, request, current_app, session, redirect, url_for, g, jsonify, abort


from . import admin_bp
from blog.models import User, Category, Post, Comment, AboutMe
from blog.utils.common import user_login_data
from ... import constants, db
from ...utils.image_storage import storage
from ...utils.response_code import RET


@admin_bp.route("/login", methods=["GET", "POST"])
def login():
    """管理端的登录页"""
    if request.method == "GET":
        # get请求代表访问登录页面，返回登录页面的模板
        # 返回模板前先判断是否有管理员登录，如果有，直接重定向到管理端的首页
        user_id = session.get("user_id", None)
        is_admin = session.get("is_admin", False)
        if user_id and is_admin:
            user = User.query.get(user_id)
            data = {
                "user": user.to_dict() if user else None
            }
            return render_template("admin/index.html", data=data)
        return render_template("admin/login.html")
    # 登录操作
    # 1.获取登录的参数
    username = request.form.get("username")
    password = request.form.get("password")
    # 2.校验参数
    if not all([username, password]):
        return render_template("admin/login.html", errmsg="用户名密码不能为空")
    # 3.查询到当前登录的用户
    try:
        user = User.query.filter(User.nick_name == username, User.is_admin == 1).first()
    except Exception as e:
        current_app.logger.error(e)
        return render_template("admin/login.html", errmsg="系统错误，请稍后再试")
    if not user:
        return render_template("admin/login.html", errmsg="无效的用户名")
    # 4.校验密码
    if not user.check_password(password):
        return render_template("admin/login.html", errmsg="用户名密码错误")
    # 5.将用户信息保存到session中
    session["user_id"] = user.id
    session["email"] = user.email
    session["nick_name"] = user.nick_name
    session["is_admin"] = True
    return redirect(url_for("admin.index"))


@admin_bp.route("/logout")
def logout():
    """管理页面的退出登录"""
    session.pop("user_id", None)
    session.pop("email", None)
    session.pop("nick_name", None)
    session.pop("is_admin", None)
    return redirect(url_for("admin.login"))


@admin_bp.route("/index")
@user_login_data
def index():
    user = g.user
    data = {
        "user": user.to_dict()
    }
    return render_template("admin/index.html", data=data)


@admin_bp.route("/user_count")
def user_count():
    """管理端的用户数据展示视图"""
    # 总人数
    total_count = 0
    try:
        total_count = User.query.filter(User.is_admin != 1).count()
    except Exception as e:
        current_app.logger.error(e)
    # 月新增用户
    mon_count = 0
    t = time.localtime()
    begin_mon_date = datetime.strptime(('%d-%02d-01' % (t.tm_year, t.tm_mon)), "%Y-%m-%d")
    try:
        mon_count = User.query.filter(User.is_admin != 1, User.create_time >= begin_mon_date).count()
    except Exception as e:
        current_app.logger.error(e)
    # 日新增用户
    day_count = 0
    begin_day_date = datetime.strptime(('%d-%02d-%02d' % (t.tm_year, t.tm_mon, t.tm_mday)), "%Y-%m-%d")
    try:
        day_count = User.query.filter(User.is_admin != 1, User.create_time >= begin_day_date).count()
    except Exception as e:
        current_app.logger.error(e)
    # 折线图数据
    active_time = []
    active_count = []
    # 取到当前这一天的开始时间数据
    today_date = datetime.strptime(('%d-%02d-%02d' % (t.tm_year, t.tm_mon, t.tm_mday)), "%Y-%m-%d")  # 今天的00:00:00
    # 循环取今天以前一个月每一天活跃的用户数量
    for i in range(0, 31):
        begin_date = today_date - timedelta(days=i)
        end_date = begin_date + timedelta(days=1)
        count = User.query.filter(User.is_admin != 1, User.last_login >= begin_date,
                                  User.last_login < end_date).count()
        active_count.append(count)
        active_time.append(begin_date.strftime('%Y-%m-%d'))
    # 反转数组，让最近的一天显示在最右边
    active_time.reverse()
    active_count.reverse()
    data = {
        "total_count": total_count,
        "mon_count": mon_count,
        "day_count": day_count,
        "active_time": active_time,
        "active_count": active_count
    }

    return render_template("admin/user_count.html", data=data)


@admin_bp.route("/user_list")
def user_list():
    """用户管理页面视图"""
    # 获取当前是第几页
    page = request.args.get("page", 1)
    try:
        page = int(page)
    except Exception as e:
        current_app.logger.error(e)
        page = 1
    # 获取用户列表信息并分页
    users = []
    user_list_dict = []
    current_page = 1
    total_page = 1
    try:
        paginate = User.query.filter(User.is_admin != 1).paginate(page, constants.ADMIN_USER_PAGE_MAX_COUNT, False)
        users = paginate.items
        current_page = paginate.page
        total_page = paginate.pages
    except Exception as e:
        current_app.logger.error(e)
    for user in users:
        user_list_dict.append(user.to_admin_dict())
    # 准备传输数据
    data = {
        "users": user_list_dict,
        "current_page": current_page,
        "total_page": total_page
    }
    return render_template("admin/user_list.html", data=data)


@admin_bp.route("/write_blog", methods=["GET", "POST"])
@user_login_data
def write_blog():
    """发布博客的视图"""
    user = g.user
    if request.method == "GET":
        # get请求表示写文章，返回写文章的页面
        # 获取到所有的分类信息
        categories = []
        try:
            categories = Category.query.all()
        except Exception as e:
            current_app.logger.error(e)
        category_list = []
        for category in categories:
            category_list.append(category.to_dict())
        data = {
            "user": user.to_dict(),
            "categories": category_list
        }
        return render_template("admin/write_blog.html", data=data)
    # post请求则表示发布文章的请求
    # 1.获取提交的数据
    form_data = request.form
    title = form_data.get("title")
    digest = form_data.get("digest")
    content = form_data.get("content")
    index_image = request.files.get("index_image")
    category_id = form_data.get("category_id")
    # 2.校验参数
    if not all([title, digest, category_id, content, index_image]):
        return jsonify(errno=RET.PARAMERR, errmsg="不能有空值")
    try:
        category_id = int(category_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.PARAMERR, errmsg="参数错误，请稍后在试")
    # 3.读取图片并上传
    try:
        index_image_data = index_image.read()
        key = storage(index_image_data)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.THIRDERR, errmsg="图片上传失败")
    # 4.创建文章对象
    article = Post()
    article.title = title
    article.content = content
    article.digest = digest
    article.index_image_url = constants.QINIU_DOMIN_PREFIX + key
    article.category_id = category_id
    article.user_id = user.id
    # 5.提交到数据库
    try:
        db.session.add(article)
        db.session.commit()
    except Exception as e:
        db.session.rollback()
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg="数据保存失败，请稍后在试")
    return jsonify(errno=RET.OK, errmsg="OK")


@admin_bp.route("/article_list")
def article_list():
    """管理页面文章的列表显示"""
    return None


@admin_bp.route("article_category", methods=["GET", "POST"])
def article_category():
    """管理文章分类的视图"""
    if request.method == "GET":
        # 查询所以的文章分类
        categories = []
        try:
            categories = Category.query.all()
        except Exception as e:
            current_app.logger.error(e)
            abort(404)
        category_dict_list = []
        for category in categories:
            category_dict_list.append(category.to_dict())
        data = {
            "categories": category_dict_list
        }
        return render_template("admin/article_category.html", data=data)
    # post请求，更改文章的分类信息
    # 1.取参数
    category_name = request.json.get("category_name")
    category_id = request.json.get("category_id")
    # 2.校验参数
    if not category_name:
        return jsonify(errno=RET.PARAMERR, errmsg="参数有误")
    if category_id:
        # 当分类的id存在，则为修改已有的分类
        try:
            category_id = int(category_id)
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.PARAMERR, errmsg="参数有误")
        try:
            category = Category.query.get(category_id)
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.DBERR, errmsg="数据库查询错误")
        if not category:
            current_app.logger.error()
            return jsonify(errno=RET.NODATA, errmsg="没有查询到相关分类信息")
        category.name = category_name
        # 提交到数据库
        try:
            db.session.add(category)
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            current_app.logger.error(e)
            return jsonify(errno=RET.DBERR, errmsg="数据库插入失败")
        return jsonify(errno=RET.OK, errmsg="编辑分类成功")
    else:
        # 新增分类信息
        category = Category()
        category.name = category_name
        try:
            db.session.add(category)
            db.session.commit()
        except Exception as e:
            current_app.logger.error(e)
            db.session.rollback()
            return jsonify(errno=RET.DBERR, errmsg="数据库插入失败")
        return jsonify(errno=RET.OK, errmsg="新增分类成功")


@admin_bp.route("/comment_list")
def comment_list():
    """获取评论审核页面"""
    # 获取当前页
    page = request.args.get("page", 1)
    try:
        page = int(page)
    except Exception as e:
        current_app.logger.error(e)
        page = 1
    comments = []
    comment_list_dict = []
    current_page = 1
    total_page = 1
    # 请求待审核的评论列表
    try:
        paginate = Comment.query.filter(Comment.status == 0)\
            .order_by(Comment.create_time.desc())\
            .paginate(page, constants.ADMIN_ARTICLE_PAGE_MAX_COUNT, False)
        comments = paginate.items
        current_page = paginate.page
        total_page = paginate.pages
    except Exception as e:

blog/modules/article/__init__.py
# 文章模块
from flask import  Blueprint

article_bp = Blueprint("article", __name__, url_prefix="/article")

from . import views

blog/modules/article/views.py
# 文章的视图
from flask import g, current_app, abort, render_template, jsonify, request

from blog.utils.common import user_login_data
from blog.utils.response_code import RET
from . import article_bp
from blog.models import Post, Comment
from ... import db


@article_bp.route("/<int:article_id>")
@user_login_data
def article_detail(article_id):
    """文章详情页的视图"""
    user = g.user
    # 查询博客文章的数据
    article = None
    try:
        article = Post.query.get(article_id)
    except Exception as e:
        current_app.logger.error(e)
    if not article:
        abort(404)  # 没有查询到文章数据，弹出404页面
    # 查到了文章数据，更新点击次数
    article.clicks += 1
    # 查询文章评论的数据
    comments = []
    try:
        comments = Comment.query.filter(Comment.post_id == article.id).order_by(Comment.create_time.desc()).all()
    except Exception as e:
        current_app.logger.error(e)
    comment_dict = []
    for comment in comments:
        comment_dict.append(comment.to_dict())
    data = {
        "user": user.to_dict() if user else None,
        "article": article.to_dict(),
        "comments": comment_dict
    }
    return render_template("blog/detail.html", data=data)


@article_bp.route("/article_comment", methods=["POST"])
@user_login_data
def article_comment():
    """文章评论的视图"""
    # 1.获取用户的登录信息
    user = g.user
    if not user:
        return jsonify(errno=RET.SESSIONERR, errmsg="用户未登录")
    # 2.获取用户的评论数据
    json_data = request.json
    article_id = json_data.get("article_id")
    comment_content = json_data.get("comment_content")
    parent_id = json_data.get("parent_id")
    # 3.校验参数
    if not all([article_id, comment_content]):
        return jsonify(errno=RET.PARAMERR, errmsg="参数错误")
    try:
        news_id = int(article_id)
        if parent_id:
            parent_id = int(parent_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.PARAMERR, errmsg="参数错误")
    # 查询到要评论的文章,看文章是否存在
    try:
        article = Post.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.NODATA, errmsg="未查询到文章数据")
    # 4.初始化评论模型
    comment = Comment()
    comment.user_id = user.id
    comment.post_id = article_id
    comment.content = comment_content
    if parent_id:
        comment.parent_id = parent_id
    # 5.添加到数据库
    try:
        db.session.add(comment)
        db.session.commit()
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg="数据库写入错误")
    # 6.返回响应
    data = comment.to_dict()
    return jsonify(errno=RET.OK, errmsg="评论成功", data=data)

blog/modules/blog/__init__.py
from flask import Blueprint

# index模块的蓝图对象
blog_bp = Blueprint("blog", __name__)

from . import views

blog/modules/index/__init__.py
from flask import Blueprint

# index模块的蓝图对象
index_bp = Blueprint("index", __name__)

from . import views

blog/utils/__init__.py
# 功能扩展包

blog/templates/blog/articles.html
{% extends 'blog/base.html' %}

{% block title %}
    文章列表
{% endblock %}

{% block css %}
{% endblock %}

{% block js %}
    <script type="text/javascript" src="../../static/blog/js/articles.js"></script>
{% endblock %}

{% block navigation %}
    <nav id="topnav" class="f_l">
        <ul>
            <a href="#">  </a>
            <a href="{{ url_for('index.index') }}">首页</a>
            <a href="#" class="topnav_current">文章</a>
            <a href="#">关于我</a>
            <a href="#">时间轴</a>
            <a href="#">给我留言</a>
        </ul>
    </nav>
{% endblock %}

{% block shuffling %}
{% endblock %}

{% block content %}
    <div class="topnews" style="margin: 0">
        <h2 id="category_title">
            <span>
                <ul class="menu">
                    {% for category in data.categories %}
                        <li style="float: left" data-cid="{{ category.id }}"><a href="javascript:;">{{ category.name }}</a></li>
                    {% endfor %}
                </ul>
            </span>
            <b>文章</b>推荐
        </h2>
        <div class="article_list">
{#            动态获取文章列表信息#}
        </div>
    </div>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block title %}
    文章详情
{% endblock %}

{% block css %}
    <link href="../../static/blog/css/detail.css" rel="stylesheet">
{% endblock %}

{% block js %}
    <script type="text/javascript" src="../../static/blog/js/detail.js"></script>
{% endblock %}

{% block content %}
    <div class="detail_con fl">
        <h3>{{ data.article.title }}</h3>
        <div class="detail_about clearfix">
            <div class="autor">
                <span class="lm f_l"><a href="/">{{ data.article.category.name }}</a></span>
                <span class="dtime f_l"><a href="/">{{ data.article.create_time }}</a></span>
                <span class="pingl f_r">{{ data.article.comments_count }}</span>
            </div>
        </div>
        <p class="summary">
            {{ data.article.digest }}
        </p>
        <div style="padding-left: 10px; padding-right: 10px">{{ data.article.content | safe }}</div>
        <p></p>
        <a href="javascript:;" class="collection block-center">收藏</a>
        <a href="javascript:;" class="collected block-center" style="display: none"><span class="out">已收藏</span><span class="over">取消收藏</span></a>
        {% if data.user %}
            <form action="" class="comment_form" data-articleid="{{ data.article.id }}">
                <div class="person_pic">
                    <img src="{% if data.user.avatar_url %}{{ data.user.avatar_url }}{% else %}../../static/blog/images/cat.jpg{% endif %}" alt="用户头像">
                </div>
                <textarea placeholder="请发表您的评论" class="comment_input"></textarea>
                <input type="submit" name="" value="评 论" class="comment_sub">
            </form>
        {% else %}
            <div class="comment_form_logout">
                登录发表你的评论
            </div>
        {% endif %}
        <div class="comment_count">
            {{ data.article.comments_count }}条评论
        </div>
        <div class="comment_list_con">
            {% for comment in data.comments %}
                <div class="comment_list">
                    <div class="person_pic fl">
                        <img src="{% if comment.user.avatar_url %}{{ comment.user.avatar_url }}{% else %}../../static/blog/images/cat.jpg{% endif %}" alt="用户图标">
                    </div>
                    <div class="user_name fl">{{ comment.user.nick_name }}</div>
                    <div class="comment_text fl">
                        {{ comment.content }}
                    </div>
                    {% if comment.parent %}
                        <div class="reply_text_con fl">
                            <div class="user_name2">{{ comment.parent.user.nick_name }}</div>
                            <div class="reply_text">
                                {{ comment.parent.content }}
                            </div>
                        </div>
                    {% endif %}
                    <div class="comment_time fl">{{ comment.create_time }}</div>
                    {% if data.user %}
                    <a href="javascript:;" class="comment_reply fr">回复</a>
                    {% endif %}
                    <from class="reply_form fl" data-commentid="{{ comment.id }}" data-articleid="{{ data.article.id }}">
                        <textarea  class="reply_input"></textarea>
                        <input type="submit" name="" value="回复" class="reply_sub fr">
                        <input type="reset" name="" value="取消" class="reply_cancel fr">
                    </from>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block shuffling %}
{% endblock %}

{% block navigation %}
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title %}
首页
{% endblock %}

{% block css %}
{% endblock %}

{% block js %}
{% endblock %}

{% block navigation %}
    <nav id="topnav" class="f_l">
        <ul>
            <a href="#">  </a>
            <a href="#" class="topnav_current">首页</a>
            <a href="{{ url_for('index.articles') }}">文章</a>
            <a href="#">关于我</a>
            <a href="#">时间轴</a>
            <a href="#">给我留言</a>
        </ul>
    </nav>
{% endblock %}

{% block content %}
    <div class="topnews">
        <h2>
            <span>
                {% for category in data.categories %}
                    <a href="/" target="_blank">{{ category.name }}</a>
                {% endfor %}
            </span>
            <b>文章</b>推荐
        </h2>
        {% for post in data.posts %}
            <div class="blogs">
                <figure><img src="{% if post.index_image_url %}{{ post.index_image_url }}{% else %}../../static/blog/images/01.jpg{% endif %}"></figure>
                <ul>
                    <h3><a href="/article/{{ post.id }}">{{ post.title }}</a></h3>
                    <p>{{ post.digest }}...</p>
                    <p class="autor"><span class="lm f_l"><a href="/">{{ post.category.name }}</a></span><span class="dtime f_l">{{ post.create_time }}</span><span class="viewnum f_r">浏览（<a href="/">{{ post.clicks }}</a>）</span><span class="pingl f_r">评论（<a href="/">30</a>）</span></p>
                </ul>
            </div>
        {% endfor %}
    </div>
{% endblock %}